#!/bin/bash
source .env
rm -r .venv

# Create virtualenv
echo -e "[INFO] Creating virtualenv\n\n"
python3 -m venv .venv

# Activate virtualenv
source .venv/bin/activate

# Upgrade pip
python3 -m pip install --upgrade pip

# Install requirements
echo -e "\n\n[INFO] Installing requirements\n\n"
python3 -m pip install -r requirements.txt

# Run the app
echo -e "\n\n[INFO] Running the app\n\n"
streamlit run app.py