#!/bin/bash
source .env

# Create virtualenv
if [ -d ".venv" ]; then
    echo -e "[INFO] Virtualenv already exists\n\n"
else
    echo -e "[INFO] Virtualenv does not exist\n\n"
    echo -e "[INFO] Creating virtualenv\n\n"
    python3 -m venv .venv
fi

# Activate virtualenv
source .venv/bin/activate

# Upgrade pip
python3 -m pip install --quiet --upgrade pip

# Install requirements
echo -e "[INFO] Installing requirements\n\n"
python3 -m pip install -q -r requirements.txt

# Run the app
echo -e "[INFO] Running the app\n\n"
python3 -m uvicorn app.main:app --reload
